FROM ubuntu:22.04

RUN apt update -y
RUN apt install -y git
RUN apt install -y swig
RUN apt install -y mingw-w64
RUN apt install -y default-jdk
RUN apt install -y python3-dev
RUN apt install -y clang-format
