name: Build and Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run build commands in container
      run: |
        ./.devcontainer/ubuntu-2204/install.sh
        cd RulesEngine/core
        make jsoncpp_build
        make windows
